In [15]:
import pandas as pd
import yaml
from pathlib import Path
import os

In [16]:
candidate_paths = Path.cwd().parent.parent / "dataset.yaml",

config_path = next((path for path in candidate_paths if path.exists()), None)
if config_path is None:
    raise FileNotFoundError("Could not find dataset.yaml from the current working directory")

with config_path.open("r") as file:
    dataset_paths = yaml.safe_load(file)

print(dataset_paths)

{'TITANIC_TRAIN': 'dataset/titanic/train.csv', 'TITANIC_TEST': 'dataset/titanic/test.csv'}

In [17]:
train_path = dataset_paths["TITANIC_TRAIN"]
test_path = dataset_paths["TITANIC_TEST"]

base_dir = '../../'

train_data = pd.read_csv(os.path.join(base_dir, train_path))
test_data = pd.read_csv(os.path.join(base_dir, test_path))

In [18]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
train_data.shape

(891, 12)

In [20]:
train_data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
train_data['Embarked'].value_counts()
train_data.fillna({'Embarked':train_data['Embarked'].mode()[0]}, inplace=True)
train_data['Cabin'].value_counts()
train_data.fillna({'Cabin':train_data['Cabin'].mode()[0]}, inplace=True)
train_data['Age'].mean()
train_data.fillna({'Age':round(train_data['Age'].mean(), 2)}, inplace=True)
train_data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [22]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,B96 B98,S

In [23]:
train_data.drop(columns=['PassengerId','Name', 'Ticket', 'Cabin'], inplace=True)
train_data.shape

(891, 8)

In [ ]:
data = pd.get_dummies(data=train_data, columns=['Pclass','Sex','SibSp','Parch','Embarked'], drop_first=True)

In [25]:
data.head()

,Age,Fare,Survived_1,Pclass_2,Pclass_3,Sex_male,SibSp_1,SibSp_2,SibSp_3,SibSp_4,SibSp_5,SibSp_8,Parch_1,Parch_2,Parch_3,Parch_4,Parch_5,Parch_6,Embarked_Q,Embarked_S
0,22.0,7.2500,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True
1,38.0,71.2833,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
2,26.0,7.9250,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,35.0,53.1000,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
4,35.0,8.0500,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [26]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [ ]:
data['Age_scaled'] = scaler.fit_transform(data[['Age']])
data['Fare_scaled'] = scaler.fit_transform(data[['Fare']])

In [31]:
data.drop(columns=['Age','Fare'], inplace=True)

In [ ]:
X = data['Survived']
Y = data.drop(columns=['Survived'])